apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-traefik-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dheenadayalan.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
    - host: edusence.contentflow.page
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: edusence-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edusence-frontend
                port:
                  number: 80

    # Rule 2: Root Domain (ContentFlow)
    - host: contentflow.page
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: affiliate-ui
                port:
                  number: 80
