apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaR2hsWlc1aGIyODNPbWRvY0Y5SGJHSkNZMlp1ZERsU2VUUkRhRTFXT0daTk0yZGFhalJOYlZaMlFXUTBSbXRJVTIwPSIKICAgIH0KICB9Cn0K