apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: ghcr-secret # Matches the secret we created above
      containers:
      - name: portfolio
        image: ghcr.io/dheenaoo7/dheenaoo7-portfolio:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
